// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZuIhY_HyQbxDa_ePA0tpSQ6qttldPDmw',
    appId: '1:753395632865:android:83c8febc2ff03cd7d445a0',
    messagingSenderId: '753395632865',
    projectId: 'fundsync-mobile-app',
    storageBucket: 'fundsync-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBoypnR_9EtJNomU-5fkww-esAoVeyI2A',
    appId: '1:753395632865:ios:b7ffda7d6c8e1a78d445a0',
    messagingSenderId: '753395632865',
    projectId: 'fundsync-mobile-app',
    storageBucket: 'fundsync-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.fundsyncefixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9YCmmC48yvGbSth_k6_VdlHXxRnu6Bfk',
    appId: '1:753395632865:web:775a4e3ac22d57f5d445a0',
    messagingSenderId: '753395632865',
    projectId: 'fundsync-mobile-app',
    authDomain: 'fundsync-mobile-app.firebaseapp.com',
    storageBucket: 'fundsync-mobile-app.firebasestorage.app',
    measurementId: 'G-ZNQ9MJPMGP',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9YCmmC48yvGbSth_k6_VdlHXxRnu6Bfk',
    appId: '1:753395632865:web:775a4e3ac22d57f5d445a0',
    messagingSenderId: '753395632865',
    projectId: 'fundsync-mobile-app',
    authDomain: 'fundsync-mobile-app.firebaseapp.com',
    storageBucket: 'fundsync-mobile-app.firebasestorage.app',
    measurementId: 'G-ZNQ9MJPMGP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBoypnR_9EtJNomU-5fkww-esAoVeyI2A',
    appId: '1:753395632865:ios:b7ffda7d6c8e1a78d445a0',
    messagingSenderId: '753395632865',
    projectId: 'fundsync-mobile-app',
    storageBucket: 'fundsync-mobile-app.firebasestorage.app',
    iosBundleId: 'com.example.fundsyncefixed',
  );

}